### ISSUE TITLE
bash: playwright: command not found

### ISSUE THREAD

**Issue by WaffleBoyQc** [sudoguy/tiktokpy#214]
https://i.imgur.com/kS4UNau.png

**Comment by sudoguy** [comment]
Hey @WaffleBoyQc!
Unfortunately, the deployment to PyPi is now broken, so you do not have the working version installed with playwright. In the coming days I will solve this problem and write here. Thanks for the report!

**Comment by sudoguy** [comment]
Version 0.9.0 uploaded to PyPi. Update version by command 
```bash
pip install -U tiktokpy
```
and try again
