### ISSUE TITLE
`tiktokpy login` does not capture login info

### ISSUE THREAD

**Issue by roguespork** [sudoguy/tiktokpy#254]
Despite running this command multiple times, even chaining it (`tiktokpy login; python3 Quickstart.py`) I cannot seem to get beyond anonymous mode. I do see my username is captured, but it does not seem to be used.

**Comment by muhammedaksam** [comment]
https://github.com/sudoguy/tiktokpy/pull/256/commits/7dd8f0739962e55215325dc2a516b91215bb243f

**Comment by roguespork** [comment]
Thank you 😄
