### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by tobeyond** [sudoguy/tiktokpy#36]
How to actually login?
It is not in quickstart. Is it possible to include the login command before the other functions in quickstart?

**Comment by sudoguy** [comment]
@tobeyond 
Login function is realized in the bot. The first time you need to do it manually using the command in the terminal 
```bash
tiktokpy login
```

A browser will open and you will need to log in. After login, the browser will close and cookies should be written to the `settings.toml` file.
Before initializing the bot, the `settings.toml` file is checked for cookies. If they are, then the bot will use them.

The next time when you run your bot will tiktokpy already logged

**Comment by tobeyond** [comment]
Thank you.
I tried as you said. The browser opens and I've logged in. But it does not close nor saves the cookies :/

**Comment by sudoguy** [comment]
It looks like a bug.  I'll try to fix it for the next release.  After login, try to hover over your avatar and click on View profile.  Maybe it will work now

**Comment by tobeyond** [comment]
Cool. So I'm not sure if it worked. I got:

>   raise IOError('Unable to remove Temporary User Data')
> OSError: Unable to remove Temporary User Data

but it actually created the cookies. So I'm trying quickstart but it's stuck in Getting trending 0%.

**Comment by sudoguy** [comment]
This bug with broken progress bar has been fixed in version 0.8.3. Update package, pls and try again
```bash
pip install -U tiktokpy
```

**Comment by tobeyond** [comment]
Still stuck forever in "Getting trending items"

**Comment by tobeyond** [comment]
The login is not working again
